### PR TITLE
Fix null website error with RelationField

### LINKED ISSUE #412: RelationField saves with website=None when creating a new site metadata
### Steps to Reproduce

- Go to `/new-site/` and create a new site using the [ocw-course starter](https://github.com/mitodl/ocw-hugo-projects/blob/main/ocw-course/ocw-studio.yaml)
- Without refreshing your browser, go to site metadata. Open the network tab in your browser and click save. In the network tab you should see a POST to `/api/websites/.../content/` with the metadata having something like `{"website": null, "content": [ ... ]}`

### Expected Behavior

The `website` should be `ocw-www`

### Actual Behavior

The `website` is saved as null

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #412 

#### What's this PR do?
 - Sets website to the correct value (which is specified in the config) when creating a new form or adding a field without data on the backend
 - Sets website to the correct value when the relation field is updated

#### How should this be manually tested?
 - Create a new website with the ocw-course starter from [here](https://github.com/mitodl/ocw-hugo-projects/blob/main/ocw-course/ocw-studio.yaml)
 - Go to metadata. You should see a relation field for instructors. (You do *not* need to populate instructors, an empty list is fine here)
- Open your network tab. Add a department number to bypass validation, then click "Save"
- In your network tab you should see a POST to create the metadata:

        {
          "type": "sitemetadata",
          "metadata": {
            "department_numbers": [
              "6"
            ],
            "instructors": {
              "website": "course-7",
              "content": []
            }
          },
          "text_id": "sitemetadata"
        }

The `website` value should be the same as the name of your site. If you run through these steps on master the value will be `null` instead

Internal menu links should also still work with no change of behavior. To verify this:
 - Create a new site using the omnibus starter
 - Create a couple resources
 - Go to "Menu" on the side. Click "Add new"
 - In the side drawer create an internal link. You should see both resources in the dropdown. You should be able to update them, refresh the page and see the changes you made persist.

### CODE REVIEW

**Comment by aliceriot** [comment]
confirmed the issue on main and then confirmed that this addresses it, reading code now

File: static/js/components/forms/SiteContentForm.tsx [hunk 1]
```diff
@@ -37,21 +38,23 @@ interface Props {
...
 }
 
 export default function SiteContentForm({
   onSubmit,
   fields,
   configItem,
   content,
-  formType
+  formType,
+  website
```
Comment (aliceriot) [inline static/js/components/forms/SiteContentForm.tsx:50]: if you want you could use the `useWebsite` hook here instead of passing in a prop

File: static/js/components/widgets/RelationField.tsx [hunk 2]
```diff
@@ -155,20 +154,26 @@ export default function RelationField(
...
+      const updatedEvent = {
+        target: {
+          name:  event.target.name.replace(/\.content$/, ""),
+          value: {
+            website: website.name,
+            content: event.target.value
+          }
+        }
       }
+      // @ts-ignore
```
Comment (aliceriot) [inline static/js/components/widgets/RelationField.tsx:173]: any way we can avoid the `@ts-ignore` here? I think generally it is a good goal for us to only use them in test files. Maybe you can add a cast on the type of `updatedEvent` or adjust the type signature for the `onChange` prop?

File: static/js/components/widgets/RelationField.tsx [hunk 3]
```diff
@@ -155,20 +154,26 @@ export default function RelationField(
...
-          website: website.name,
-          content
-        })
+      // When we run renameNestedFields we add a '.content' suffix to the name of the field for RelationField
+      // because the data structure looks like this: { content, website }
+      // where 'content' is either a string or a list of strings.
+      // Validation by yup is easier to work with when the field name ends with .content because
+      // formik validates the value of 'content' instead of '{ content, website }'.
+      // But while that's easier for validation, we still need to send the whole object.
+      // So we need to remove that .content suffix and also add back 'website' when onChange is called.
```
Comment (aliceriot) [inline static/js/components/widgets/RelationField.tsx:163]: thanks for updating this comment :)

**Review by aliceriot — CHANGES_REQUESTED** [review]
a few comments / questions

File: static/js/components/forms/SiteContentForm.tsx (hunk 1 above)
Comment (noisecapella) [reply static/js/components/forms/SiteContentForm.tsx:50]: It works fine but I think we would need to rewrite many of the tests in `SiteContentForm.test.tsx` because it would require `helper.configureRenderer`. I think some things like whether `isSubmitting` is disabling the button become impossible to test since we would not have access to the inner function anymore

File: static/js/components/widgets/RelationField.tsx (hunk 2 above)
Comment (noisecapella) [reply static/js/components/widgets/RelationField.tsx]: Yes, it was not in the prop types actually so it should be easy to fix

File: static/js/components/forms/SiteContentForm.tsx (hunk 1 above)
Comment (aliceriot) [reply static/js/components/forms/SiteContentForm.tsx:50]: hmm what if we did a `jest.mock` on `useWebsite` and just made it return a website we made with out website factory?

Comment (aliceriot) [reply static/js/components/forms/SiteContentForm.tsx:50]: possibly that would let us still use the shallow renderer

Comment (noisecapella) [reply static/js/components/forms/SiteContentForm.tsx:50]: That's an interesting idea, I'll try that

Comment (noisecapella) [reply static/js/components/forms/SiteContentForm.tsx]: It worked out, I updated the tests for it

**Review by aliceriot — CHANGES_REQUESTED** [review]
ack wrote this comment a bit ago but didn't submit the review!

File: static/js/components/widgets/RelationField.tsx [hunk 4]
```diff
@@ -155,20 +155,25 @@ export default function RelationField(
...
+          value: {
+            website: website.name,
+            content: event.target.value
+          }
+        }
       }
+      onChange(updatedEvent)
     },
-    [setFieldValue, onChange, name, website]
+    [onChange, website]
```
[the remark this answers is not in the document]
Comment (aliceriot) [reply static/js/components/widgets/RelationField.tsx:176]: can we / should we in this PR

[the remark this answers is not in the document]
Comment (noisecapella) [reply static/js/components/widgets/RelationField.tsx]: Looks like I need to adjust `FileUploadField` and `BooleanField`. I'll try it out and see if it worked out

[the remark this answers is not in the document]
Comment (noisecapella) [reply static/js/components/widgets/RelationField.tsx]: Ok I think that's everything. I checked a site using the omnibus starter and the boolean field still works there, as well as the file fields in the resources

**Review by aliceriot — APPROVED** [review]
LGTM! 👍
