### PR TITLE
Only show "Add resource" button when attach field is set

### LINKED ISSUE #529: "Add resource" button in CKEditor should not be visible if there is no attach field
### Steps to Reproduce

View the course description field at https://ocw-studio-rc.odl.mit.edu/sites/res-8-001-applied-geometric-algebra-spring-2009/type/metadata/. There is a button "Add Resource" which exists but is not functional. 

### Expected Behavior

The "Add resource" button should only show up when the resource picker dialog is available, which is when the `attach` field is set in the site config.

### Actual Behavior

The button shows up regardless of configuration

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes #529 

#### What's this PR do?
Hides the Add resource button 

#### How should this be manually tested?
For any of the imported courses, add a new page. You should see a "Add resource" button in the "Body" section of the UI. Click it and a modal should show up.

Go to the site metadata for the same course. You should not see an "Add resource" button on the course description field.

### CODE REVIEW

File: static/js/components/widgets/MarkdownEditor.tsx [hunk 1]
```diff
@@ -103,11 +113,12 @@ export default function MarkdownEditor(props: Props): JSX.Element {
         onReady={setEditorRef}
         onChange={onChangeCB}
       />
-      {attach && attach.length > 0 ? (
+      {hasAttach ? (
         <ResourcePickerDialog
           open={resourcePickerOpen}
           setOpen={setResourcePickerOpen}
           insertEmbed={addResourceEmbed}
+          // @ts-ignore
```
Comment (alicewriteswrongs) [inline static/js/components/widgets/MarkdownEditor.tsx:121]: I think you can get rid of the `@ts-ignore` here if you inline the value of `hasAttach` (`attach && attach.length > 0`) - I think typescript is just not quite smart enough to figure that one out

you could also probably do an `attach as string` type coercion

File: static/js/components/widgets/MarkdownEditor.tsx [hunk 2]
```diff
@@ -69,10 +73,16 @@ export default function MarkdownEditor(props: Props): JSX.Element {
       // and then use it to render resources within the editor.
       return {
         ...FullEditorConfig,
-        resourceEmbed: { renderResourceEmbed, openResourcePicker }
+        resourceEmbed: { renderResourceEmbed, openResourcePicker },
+        toolbar:       {
+          ...FullEditorConfig.toolbar,
+          items: FullEditorConfig.toolbar.items.filter(item =>
+            hasAttach ? true : item !== ADD_RESOURCE
```
Comment (alicewriteswrongs) [inline static/js/components/widgets/MarkdownEditor.tsx:80]: maybe `hasAttach || item !== ADD_RESOURCE` ?

**Review by alicewriteswrongs — CHANGES_REQUESTED** [review]
two questions / suggestions

**Comment by noisecapella** [comment]
@alicewriteswrongs comments addressed

**Review by alicewriteswrongs — APPROVED** [review]
lgtm! 👍
